// <auto-generated />
using System;
using EenVoudigeToDoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EenVoudigeToDoApi.Data
{
    [DbContext(typeof(DataContext))]
    [Migration("20220621062055_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("EenVoudigeToDoApi.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("EenVoudigeToDoApi.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creatie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LaatsteAanpassing")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VervalDatum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ToDo");
                });

            modelBuilder.Entity("EenVoudigeToDoApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("EenVoudigeToDoApi.Models.Board", b =>
                {
                    b.HasOne("EenVoudigeToDoApi.Models.User", null)
                        .WithMany("Boards")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("EenVoudigeToDoApi.Models.ToDo", b =>
                {
                    b.HasOne("EenVoudigeToDoApi.Models.Board", null)
                        .WithMany("ToDos")
                        .HasForeignKey("BoardId");

                    b.HasOne("EenVoudigeToDoApi.Models.User", null)
                        .WithMany("ToDos")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("EenVoudigeToDoApi.Models.Board", b =>
                {
                    b.Navigation("ToDos");
                });

            modelBuilder.Entity("EenVoudigeToDoApi.Models.User", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("ToDos");
                });
#pragma warning restore 612, 618
        }
    }
}
